// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travel.Models;

namespace Travel.Migrations
{
    [DbContext(typeof(TravelContext))]
    [Migration("20221024173612_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Travel.Models.Place", b =>
                {
                    b.Property<int>("PlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("PlaceId");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            PlaceId = 1,
                            Country = "Italy",
                            Name = "Venice",
                            Rating = 3
                        },
                        new
                        {
                            PlaceId = 2,
                            Country = "Italy",
                            Name = "Rome",
                            Rating = 5
                        },
                        new
                        {
                            PlaceId = 3,
                            Country = "Canada",
                            Name = "Toronto",
                            Rating = 2
                        },
                        new
                        {
                            PlaceId = 4,
                            Country = "United States",
                            Name = "Toledo",
                            Rating = 4
                        },
                        new
                        {
                            PlaceId = 5,
                            Country = "United States",
                            Name = "Buffalo",
                            Rating = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
